# SwiftLint Configuration for Remission project
# Swift 6 compatible configuration with strict style rules

disabled_rules:
  - trailing_whitespace
  - force_cast
  - trailing_comma
  - explicit_type_interface
  - todo
  - opening_brace

opt_in_rules:
  - closure_spacing
  - missing_docs
  - empty_count
  - static_over_final_class

analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self

# Paths to include in linting
included:
  - Remission
  - RemissionTests
  - RemissionUITests

# Paths to exclude from linting
excluded:
  - Pods
  - Carthage
  - .build
  - Build
  - DerivedData

# Global settings
allow_zero_lintable_files: false
strict: false
lenient: false
check_for_updates: false

# Rule-specific configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - x
    - y
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - iPhone

force_try:
  severity: warning

# Reporter format for Xcode integration
reporter: "xcode"
